# Generated by Django 5.1.2 on 2024-11-08 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=44, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Trainer_images')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('fitness_certificate', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(blank=True, default='active', max_length=33, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.logindetails')),
            ],
        ),
    ]
