# Generated by Django 5.1.2 on 2024-12-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0003_tutorials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorials',
            old_name='videos',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='tutorials',
            name='image',
        ),
    ]
