# Generated by Django 5.1.2 on 2024-12-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0004_rename_videos_tutorials_media_remove_tutorials_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
