# Generated by Django 5.1.2 on 2024-12-12 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0006_alter_trainerregistration_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='connect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trainer.trainerregistration'),
        ),
    ]
