# Generated by Django 5.1.2 on 2024-11-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist_details',
            name='address',
        ),
        migrations.RemoveField(
            model_name='specialist_details',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='specialist_details',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='specialist_details',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='specialist_details',
            name='major_in',
        ),
        migrations.RemoveField(
            model_name='specialist_details',
            name='previous_experience',
        ),
        migrations.AddField(
            model_name='specialist_details',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='pic_specialist'),
        ),
        migrations.AddField(
            model_name='specialist_details',
            name='dob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist_details',
            name='exp_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='pic_specialist'),
        ),
        migrations.AddField(
            model_name='specialist_details',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist_details',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='specialist_details',
            name='idproof',
            field=models.ImageField(blank=True, null=True, upload_to='pic_specialist'),
        ),
        migrations.AddField(
            model_name='specialist_details',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pic_specialist'),
        ),
        migrations.AddField(
            model_name='specialist_details',
            name='specialization',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='specialist_details',
            name='qualification',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
