# Generated by Django 5.1.2 on 2024-12-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
