# Generated by Django 5.1.2 on 2024-12-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0002_alter_user_details_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='is_active',
        ),
    ]
