# Generated by Django 5.1.2 on 2024-12-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0005_remove_user_details_status_alter_user_details_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='key',
            new_name='USER',
        ),
    ]
