# Generated by Django 5.1.1 on 2025-01-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0008_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
