# Generated by Django 5.1.2 on 2024-12-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='status',
        ),
    ]
