# Generated by Django 5.1.2 on 2024-12-21 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_remove_logindetails_status'),
        ('Public', '0004_alter_user_details_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='trainer_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trainer.trainerregistration'),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='user_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_details', to='Public.user_details'),
        ),
    ]
